server:
  port: 8666
  servlet:
    context-path: /springboottest
#cas:
#  server-url-prefix: http://cas-server-url
#  server-login-url: http://cas-server-url/login
#  client-host-url: http://cas-client-application-host // cas服务器通过这个关联ticket信息，需要保证后续请求cas服务器的host都是这个
#  validation-type: CAS
cas:
  serverName: http://10.125.193.78:8081
  casServerUrlPrefix: http://unifiedprotal.10010sh.cn/cas
  casServerLoginUrl: http://unifiedprotal.10010sh.cn/cas/login

spring:
  redis:
    host: 'localhost'
    password: '123456'
    port: 6379
    database: 0
    timeout: 5000